spring.application.name=furniro

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.datasource.url=jdbc:postgresql://localhost:5432/furniro
spring.datasource.username=thove
spring.datasource.password=password1234

spring.flyway.fail-on-missing-locations=true
spring.flyway.baseline-on-migrate=true
logging.level.org.flywaydb=DEBUG

spring.jpa.hibernate.ddl-auto=none